### ISSUE TITLE
Error when remounting containers

### ISSUE THREAD

**Issue by Ledzz** [pmndrs/uikit#140]
I guess it could be related to #117.

When I remount some containers, I sometimes get an error: Uncaught RangeError: offset is out of bounds.
It happens on [this](https://github.com/pmndrs/uikit/blob/main/packages/uikit/src/panel/instanced-panel-group.ts#L138) line.
I logged some variables: index is -1, bucket.offset is -1, indexInBucket is 0.
I can't reproduce it outside my app yet, but if you can't find the issue I'll try to build repro again.
Uikit version is latest for now: 0.8.1
Also I'll attach whole error with stacktrace:
```
helpers.ts:122 Uncaught RangeError: offset is out of bounds
    at Float32Array.set (<anonymous>)
    at InstancedBufferAttribute.set (three.module.js:9961:14)
    at instanced-panel-group.js:95:27
    at updateSortedBucketsAllocation (sorted-buckets.js:151:13)
    at InstancedPanelGroup.update (instanced-panel-group.js:198:13)
    at InstancedPanelGroup.onFrame (instanced-panel-group.js:174:14)
    at instanced-panel-group.js:38:66
    at PanelGroupManager.traverse (instanced-panel-group.js:46:17)
    at onFrame (instanced-panel-group.js:38:40)
    at Object.current (root.js:44:13)
    at render$1 (index-6662eaf2.esm.js:1511:22)
    at loop (index-6662eaf2.esm.js:1538:19)
```

**Comment by Ledzz** [comment]
Yeah, the #117 issue has been fixed. I just found this one and it is a different error.
I'll try to replicate it in codesandbox this week :)

**Comment by bbohlender** [comment]
Awesome, thank you :)
