### ISSUE TITLE
unable to run examples locally

### ISSUE THREAD

**Issue by manuschillernordlb** [pmndrs/uikit#22]
Currently I am on the current main (1e2b12bc096fbb3a764031c8e17d610326f73855) and ran `pnpm i`in the workspace root

This gives me several warnings:

```bash
 pnpm i
Scope: all 14 workspace projects
Lockfile is up to date, resolution step is skipped
Already up to date
 WARN  Failed to create bin at /Users/User/code/sandbox/uikit/examples/apfel/node_modules/.bin/uikit. ENOENT: no such file or directory, open '/Users/User/code/sandbox/uikit/packages/uikit/dist/cli/index.js'
 WARN  Failed to create bin at /Users/User/code/sandbox/uikit/examples/auth/node_modules/.bin/uikit. ENOENT: no such file or directory, open '/Users/User/code/sandbox/uikit/packages/uikit/dist/cli/index.js'
 WARN  Failed to create bin at /Users/User/code/sandbox/uikit/examples/dashboard/node_modules/.bin/uikit. ENOENT: no such file or directory, open '/Users/User/code/sandbox/uikit/packages/uikit/dist/cli/index.js'
 WARN  Failed to create bin at /Users/User/code/sandbox/uikit/examples/lucide/node_modules/.bin/uikit. ENOENT: no such file or directory, open '/Users/User/code/sandbox/uikit/packages/uikit/dist/cli/index.js'
 WARN  Failed to create bin at /Users/User/code/sandbox/uikit/examples/card/node_modules/.bin/uikit. ENOENT: no such file or directory, open '/Users/User/code/sandbox/uikit/packages/uikit/dist/cli/index.js'
 WARN  17 other warnings
Done in 609ms
```

When I then try to run any example I get the following error:

```bash
❯ cd examples/apfel
❯ pnpm i
Scope: all 14 workspace projects
 WARN  Failed to create bin at /Users/User/code/sandbox/uikit/examples/apfel/node_modules/.bin/uikit. ENOENT: no such file or directory, open '/Users/User/code/sandbox/uikit/packages/uikit/dist/cli/index.js'
 WARN  Failed to create bin at /Users/User/code/sandbox/uikit/examples/auth/node_modules/.bin/uikit. ENOENT: no such file or directory, open '/Users/User/code/sandbox/uikit/packages/uikit/dist/cli/index.js'
 WARN  Failed to create bin at /Users/User/code/sandbox/uikit/examples/card/node_modules/.bin/uikit. ENOENT: no such file or directory, open '/Users/User/code/sandbox/uikit/packages/uikit/dist/cli/index.js'
 WARN  Failed to create bin at /Users/User/code/sandbox/uikit/examples/default/node_modules/.bin/uikit. ENOENT: no such file or directory, open '/Users/User/code/sandbox/uikit/packages/uikit/dist/cli/index.js'
 WARN  Failed to create bin at /Users/User/code/sandbox/uikit/examples/dashboard/node_modules/.bin/uikit. ENOENT: no such file or directory, open '/Users/User/code/sandbox/uikit/packages/uikit/dist/cli/index.js'
 WARN  17 other warnings
Done in 608ms
❯ pnpm dev

> @ dev /Users/User/code/sandbox/uikit/examples/apfel
> vite --host

error when starting dev server:
Error: Failed to resolve entry for package "@react-three/uikit-lucide". The package may have incorrect main/module/exports specified in its package.json.
    at packageEntryFailure (file:///Users/User/code/sandbox/uikit/node_modules/.pnpm/vite@5.0.12_@types+node@20.11.0/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:29443:17)
    at resolvePackageEntry (file:///Users/User/code/sandbox/uikit/node_modules/.pnpm/vite@5.0.12_@types+node@20.11.0/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:29440:5)
    at tryNodeResolve (file:///Users/User/code/sandbox/uikit/node_modules/.pnpm/vite@5.0.12_@types+node@20.11.0/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:29210:20)
    at Context.resolveId (file:///Users/User/code/sandbox/uikit/node_modules/.pnpm/vite@5.0.12_@types+node@20.11.0/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:28978:28)
    at Object.resolveId (file:///Users/User/code/sandbox/uikit/node_modules/.pnpm/vite@5.0.12_@types+node@20.11.0/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:63987:64)
    at async file:///Users/User/code/sandbox/uikit/node_modules/.pnpm/vite@5.0.12_@types+node@20.11.0/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:68003:21
    at async file:///Users/User/code/sandbox/uikit/node_modules/.pnpm/vite@5.0.12_@types+node@20.11.0/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:64644:20
    at async addManuallyIncludedOptimizeDeps (file:///Users/User/code/sandbox/uikit/node_modules/.pnpm/vite@5.0.12_@types+node@20.11.0/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:65837:31)
    at async createDepsOptimizer (file:///Users/User/code/sandbox/uikit/node_modules/.pnpm/vite@5.0.12_@types+node@20.11.0/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:64885:9)
    at async initDepsOptimizer (file:///Users/User/code/sandbox/uikit/node_modules/.pnpm/vite@5.0.12_@types+node@20.11.0/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:64785:9)
 ELIFECYCLE  Command failed with exit code 1.
```

**My System:**
I am on a M2 Max, Sonoma 14.3, pnpm 8.15.4, node v20.7.0

**Comment by bbohlender** [comment]
Have you followed the setup guide in CONTRIBUTION.md?
In case you just want to try out the examples, they are all hosted and can be accessed through the docs.

**Comment by manuschillernordlb** [comment]
ahh no, I haven't - sorry. 

Following the setup guide in CONTRIBUTION.md works great and I can run the examples locally. Thanks a lot!
