### ISSUE TITLE
can't run pnpm dev

### ISSUE THREAD

**Issue by Kusou1** [pmndrs/uikit#7]
node version:16.20.2
pnpm version:8.15.4

`
> @ dev /Users/zhangshaohong/test/uikit/examples/dashboard
> vite --host

error when starting dev server:
Error: fetch is not set. Please pass a fetch implementation as new Octokit({ request: { fetch }}). Learn more at https://github.com/octokit/octokit.js/#fetch-missing
    at fetchWrapper (/Users/zhangshaohong/test/uikit/node_modules/.pnpm/@octokit+request@8.2.0/node_modules/@octokit/request/dist-node/index.js:69:11)
    at request2 (/Users/zhangshaohong/test/uikit/node_modules/.pnpm/@octokit+request@8.2.0/node_modules/@octokit/request/dist-node/index.js:198:14)
    at /Users/zhangshaohong/test/uikit/node_modules/.pnpm/@octokit+plugin-request-log@4.0.0_@octokit+core@5.1.0/node_modules/@octokit/plugin-request-log/dist-node/index.js:37:12
    at /Users/zhangshaohong/test/uikit/node_modules/.pnpm/before-after-hook@2.2.3/node_modules/before-after-hook/lib/register.js:25:15
    at async _GithubSource.getSourceInfo (file:///Users/zhangshaohong/test/uikit/node_modules/.pnpm/vite-plugin-mkcert@1.17.4_vite@5.0.12/node_modules/vite-plugin-mkcert/dist/mkcert.mjs:263:22)
    at async _Mkcert.getSourceInfo (file:///Users/zhangshaohong/test/uikit/node_modules/.pnpm/vite-plugin-mkcert@1.17.4_vite@5.0.12/node_modules/vite-plugin-mkcert/dist/mkcert.mjs:535:24)
    at async _Mkcert.initMkcert (file:///Users/zhangshaohong/test/uikit/node_modules/.pnpm/vite-plugin-mkcert@1.17.4_vite@5.0.12/node_modules/vite-plugin-mkcert/dist/mkcert.mjs:543:24)
    at async _Mkcert.init (file:///Users/zhangshaohong/test/uikit/node_modules/.pnpm/vite-plugin-mkcert@1.17.4_vite@5.0.12/node_modules/vite-plugin-mkcert/dist/mkcert.mjs:529:7)
    at async config (file:///Users/zhangshaohong/test/uikit/node_modules/.pnpm/vite-plugin-mkcert@1.17.4_vite@5.0.12/node_modules/vite-plugin-mkcert/dist/mkcert.mjs:638:7)
    at async runConfigHook (file:///Users/zhangshaohong/test/uikit/node_modules/.pnpm/vite@5.0.12_@types+node@20.11.0/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:68420:25)
 ELIFECYCLE  Command failed with exit code 1.
`

**Comment by bbohlender** [comment]
this example requires node 18 because it uses vite mkcert (which requires fetch) to be able to run in WebXR
other examples should work without node 18

**Comment by neolectron** [comment]
Just stumbled into the same issue so I added engine version in the package.json of the monorepo, so you're getting a message whenever you try to install the modules.
what do you think ? #10

**Comment by bbohlender** [comment]
Sorry, I was wrong, I removed WebXR from the example earlier, so it doesn't need mkcert anymore
Fixed in 4e09568de3197da34c37451b412d960de9d48237
